version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_myshop
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_myshop
      MYSQL_USER: user_myshop
      MYSQL_PASSWORD: root
    # volumes:
    #   - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"